# Generated by Django 3.2.5 on 2022-02-09 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etl', '0010_auto_20211125_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExtractionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('extraction_type', models.CharField(choices=[('field', 'Field'), ('table_rows', 'Table Rows'), ('table_columns', 'Table Columns')], default='field', max_length=20)),
                ('scope', models.CharField(max_length=100)),
                ('rules', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='workbooks')),
                ('file_with_corrections', models.FileField(null=True, upload_to='corrections')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('failed', 'Failed'), ('completed', 'Completed'), ('completed_with_errors', 'Needs Corrections'), ('processing', 'Processing')], default='queued', max_length=30)),
                ('errors', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkbookConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Workbook Configuration',
                'verbose_name_plural': 'Workbook Configurations',
            },
        ),
        migrations.CreateModel(
            name='WorksheetConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('sheet_name', models.CharField(max_length=100)),
                ('sheet_order', models.IntegerField(default=0)),
                ('workbook_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.workbookconfiguration')),
            ],
            options={
                'verbose_name': 'Worksheet Configuration',
                'verbose_name_plural': 'Worksheet Configurations',
            },
        ),
        migrations.AddIndex(
            model_name='workbookconfiguration',
            index=models.Index(fields=['code', 'version'], name='etl_workboo_code_a4ed4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workbookconfiguration',
            unique_together={('code', 'version')},
        ),
        migrations.AddField(
            model_name='workbook',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etl.workbookconfiguration'),
        ),
        migrations.AddField(
            model_name='workbook',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataextractionconfiguration',
            name='worksheet_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.worksheetconfiguration'),
        ),
        migrations.AlterUniqueTogether(
            name='worksheetconfiguration',
            unique_together={('code', 'workbook_configuration')},
        ),
    ]
