# Generated by Django 3.2.5 on 2022-02-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0011_auto_20220210_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workbook',
            name='errors',
        ),
        migrations.AddField(
            model_name='dataextractionconfiguration',
            name='custom_etl_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dataextractionconfiguration',
            name='custom_validation_form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workbook',
            name='file_errors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='workbook',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='file_with_corrections',
            field=models.FileField(blank=True, null=True, upload_to='corrections'),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='status',
            field=models.CharField(choices=[('new', 'Newly Uploaded'), ('queued', 'Queued'), ('failed', 'Failed'), ('completed', 'Completed'), ('completed_with_errors', 'Needs Corrections'), ('processing', 'Processing')], default='new', max_length=30),
        ),
    ]
