# Generated by Django 3.2.5 on 2022-02-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0014_dataextractionconfiguration_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worksheetconfiguration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='worksheetconfiguration',
            name='code',
        ),
    ]
