# Generated by Django 4.0.5 on 2022-10-19 07:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0029_alter_dataextractionconfiguration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALWANStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('corner_1', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('corner_2', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('gps_datum', models.CharField(default='WGS84', max_length=200, verbose_name='GPS Datum')),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('type_of_management', models.CharField(choices=[('None', 'None'), ('Locally Managed MPA', 'Locally Managed MPA'), ('Nationally Managed MPA', 'Nationally Managed MPA')], max_length=200)),
            ],
            options={
                'verbose_name': 'ALWAN Survey Station',
                'verbose_name_plural': 'ALWAN Survey Stations',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(max_length=200)),
                ('barangay', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(default='Philippines', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ALWANSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('team_leader_name', models.CharField(max_length=200)),
                ('team_leader_contact', models.CharField(max_length=200)),
                ('team_scientist_name', models.CharField(max_length=200)),
                ('volunteer_1', models.CharField(max_length=200)),
                ('volunteer_2', models.CharField(max_length=200)),
                ('volunteer_3', models.CharField(max_length=200)),
                ('volunteer_4', models.CharField(blank=True, max_length=200, null=True)),
                ('volunteer_5', models.CharField(blank=True, max_length=200, null=True)),
                ('volunteer_6', models.CharField(blank=True, max_length=200, null=True)),
                ('curated', models.BooleanField(default=False)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredb.alwanstation')),
                ('workbook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etl.workbook')),
            ],
            options={
                'verbose_name': 'ALWAN Survey',
                'verbose_name_plural': 'ALWAN Surveys',
            },
        ),
        migrations.AddField(
            model_name='alwanstation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredb.location'),
        ),
    ]
