# Generated by Django 4.0.5 on 2022-10-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredb', '0002_alwanstation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alwansurvey',
            old_name='team_leader_contact',
            new_name='team_leader_contact_number',
        ),
    ]
