# Generated by Django 4.0.5 on 2022-10-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredb', '0003_rename_team_leader_contact_alwansurvey_team_leader_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='alwansurvey',
            name='database_number',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
