# Generated by Django 4.0.5 on 2022-09-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0002_curation_delete_submitevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='verdict',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30),
        ),
    ]
