# Generated by Django 3.0.3 on 2021-06-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_etlfile_result_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('drive_id', models.TextField(null=True)),
                ('drive_url', models.URLField()),
                ('file', models.FileField(null=True, upload_to='drive')),
                ('failed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
