# Generated by Django 3.0.3 on 2021-06-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_googledrivefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googledrivefile',
            name='failed',
        ),
        migrations.AddField(
            model_name='googledrivefile',
            name='downloaded',
            field=models.BooleanField(default=True),
        ),
    ]
