# Generated by Django 3.0.3 on 2021-06-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_auto_20210621_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledrivefile',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
