# Generated by Django 3.2.4 on 2021-07-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_auto_20210621_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacapturepoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datacapturepoint',
            name='requirements',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='etlfile',
            name='errors',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='etlfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='etlfilerow',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='etlfilerow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='etlfilerow',
            name='warnings',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='googledrivefile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
