# Generated by Django 3.2.4 on 2021-07-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_auto_20210706_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValueStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('sheet_name', models.CharField(max_length=64)),
                ('code', models.TextField()),
                ('data', models.JSONField(null=True)),
                ('etlfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.etlfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
