# Generated by Django 3.2.4 on 2021-08-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_keyvaluestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcpcollection',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcpcollection',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etlfile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Queued'), (1, 'With Errors'), (2, 'Completed'), (3, 'Processing')], default=0),
        ),
    ]
