# Generated by Django 3.2.5 on 2022-02-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0013_auto_20220223_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataextractionconfiguration',
            name='name',
            field=models.CharField(default='Basic Data', max_length=200),
            preserve_default=False,
        ),
    ]
