# Generated by Django 4.0.5 on 2022-06-17 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0015_auto_20220223_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracteddata',
            name='etlfile',
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='workbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etl.workbook'),
            preserve_default=False,
        ),
    ]
