# Generated by Django 4.0.5 on 2022-06-29 20:27

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0017_remove_extracteddata_sheet_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='entry_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
