# Generated by Django 4.0.5 on 2022-07-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0018_extracteddata_entry_number_alter_extracteddata_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataextractionconfiguration',
            options={'verbose_name': 'Worksheet Section', 'verbose_name_plural': 'Worksheet Section'},
        ),
        migrations.AlterModelOptions(
            name='workbookconfiguration',
            options={'verbose_name': 'Workbook Layout', 'verbose_name_plural': 'Workbook Layouts'},
        ),
        migrations.AlterModelOptions(
            name='worksheetconfiguration',
            options={'verbose_name': 'Worksheet Layout', 'verbose_name_plural': 'Worksheet Layouts'},
        ),
        migrations.AddField(
            model_name='dataextractionconfiguration',
            name='section_order',
            field=models.IntegerField(default=0),
        ),
    ]
