# Generated by Django 4.0.5 on 2022-07-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0020_datafield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('numeric', 'Numeric')], max_length=20),
        ),
    ]
