# Generated by Django 4.0.5 on 2022-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0021_alter_datafield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataextractionconfiguration',
            name='scope',
            field=models.CharField(default='A1:B10', max_length=10),
        ),
        migrations.AddField(
            model_name='datafield',
            name='cell',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
