# Generated by Django 4.0.5 on 2022-08-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0023_alter_workbookconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workbookconfiguration',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='worksheetconfiguration',
            options={'ordering': ['workbook_configuration', 'sheet_order']},
        ),
        migrations.RemoveField(
            model_name='dataextractionconfiguration',
            name='rules',
        ),
    ]
