# Generated by Django 4.0.5 on 2022-10-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0024_alter_workbookconfiguration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=100)),
                ('error', models.TextField()),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.dataextractionconfiguration')),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.workbook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
