# Generated by Django 4.0.5 on 2022-10-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0025_extractionerror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workbook',
            name='file_errors',
        ),
        migrations.RemoveField(
            model_name='workbook',
            name='validation_errors',
        ),
        migrations.AddField(
            model_name='extractionerror',
            name='field_error',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='status',
            field=models.CharField(choices=[('new', 'Newly Uploaded'), ('queued', 'Queued'), ('failed', 'Failed'), ('completed', 'Completed'), ('corrections_needed', 'Needs Corrections'), ('processing', 'Processing')], default='new', max_length=30),
        ),
    ]
