# Generated by Django 4.0.5 on 2022-10-16 15:22

from django.db import migrations, models
import etl.validators


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0027_alter_extractionerror_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments', validators=[etl.validators.validate_workbook_attachment]),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='file',
            field=models.FileField(upload_to='workbooks', validators=[etl.validators.validate_workbook_extension]),
        ),
    ]
