# Generated by Django 4.0.5 on 2022-10-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0029_alter_dataextractionconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbookconfiguration',
            name='component',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
