# Generated by Django 3.2.5 on 2021-10-25 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coastal_stability',
            options={'verbose_name_plural': 'Coastal Stability'},
        ),
        migrations.AlterModelOptions(
            name='connectivity',
            options={'verbose_name_plural': 'Connectivity'},
        ),
        migrations.AlterModelOptions(
            name='coral_deep',
            options={'verbose_name_plural': 'Deep Coral'},
        ),
        migrations.AlterModelOptions(
            name='coral_shallow',
            options={'verbose_name_plural': 'Shallow Coral'},
        ),
        migrations.AlterModelOptions(
            name='fish_biology',
            options={'verbose_name_plural': 'Fish Biology'},
        ),
        migrations.AlterModelOptions(
            name='fish_density',
            options={'verbose_name_plural': 'Fish Density'},
        ),
        migrations.AlterModelOptions(
            name='fish_species',
            options={'verbose_name_plural': 'Fish Species'},
        ),
        migrations.AlterModelOptions(
            name='mangrove',
            options={'verbose_name_plural': 'Mangrove'},
        ),
        migrations.AlterModelOptions(
            name='mangrove_data',
            options={'verbose_name_plural': 'Mangrove Data'},
        ),
        migrations.AlterModelOptions(
            name='seagrass_cover',
            options={'verbose_name_plural': 'Seagrass Cover'},
        ),
        migrations.AlterModelOptions(
            name='seagrass_density',
            options={'verbose_name_plural': 'Seagrass Density'},
        ),
    ]
