# Generated by Django 3.2.5 on 2021-11-25 12:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coredb', '0002_auto_20211025_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='AL1Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('team_leader', models.CharField(max_length=200)),
                ('team_scientist', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'AL1 Survey',
                'verbose_name_plural': 'AL1 Surveys',
            },
        ),
        migrations.CreateModel(
            name='Photoquadrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('image_label', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cot', models.IntegerField()),
                ('diseased', models.IntegerField()),
                ('bleached', models.IntegerField()),
                ('blast_fishing_craters', models.IntegerField()),
                ('anchor_damage_craters', models.IntegerField()),
                ('trash', models.IntegerField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredb.al1survey')),
            ],
            options={
                'verbose_name': 'Photoquadrat',
                'verbose_name_plural': 'Photoquadrats',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('gps_datum', models.CharField(max_length=200)),
                ('start_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('reef_name', models.CharField(blank=True, max_length=200, null=True)),
                ('barangay', models.CharField(blank=True, max_length=200, null=True)),
                ('town', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('type_of_management', models.CharField(choices=[('None', 'None'), ('Locally Managed MPA', 'Locally Managed MPA'), ('Nationally Managed MPA', 'Nationally Managed MPA')], max_length=200)),
                ('additional_information', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Survey Station',
                'verbose_name_plural': 'Survey Stations',
            },
        ),
        migrations.CreateModel(
            name='PhotoquadratPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('major_category', models.CharField(max_length=200)),
                ('photoquadrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredb.photoquadrat')),
            ],
            options={
                'verbose_name': 'Photoquadrat',
                'verbose_name_plural': 'Photoquadrats',
            },
        ),
        migrations.CreateModel(
            name='InvertebrateCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('volunteer', models.CharField(max_length=200)),
                ('species_name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredb.al1survey')),
            ],
            options={
                'verbose_name': 'Invertebrate Count',
                'verbose_name_plural': 'Invertebrate Counts',
            },
        ),
        migrations.CreateModel(
            name='FishCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('volunteer', models.CharField(max_length=200)),
                ('species_name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredb.al1survey')),
            ],
            options={
                'verbose_name': 'Fish Count',
                'verbose_name_plural': 'Fish Counts',
            },
        ),
        migrations.AddField(
            model_name='al1survey',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredb.station'),
        ),
    ]
