# Generated by Django 3.2.5 on 2021-11-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredb', '0003_auto_20211125_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='al1survey',
            name='curated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='gps_datum',
            field=models.CharField(default='WGS84', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('start_point', 'end_point')},
        ),
    ]
