# Generated by Django 3.2.5 on 2021-11-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredb', '0004_auto_20211126_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoquadratpoint',
            options={'verbose_name': 'Photoquadrat Point', 'verbose_name_plural': 'Photoquadrats Points'},
        ),
        migrations.AddField(
            model_name='station',
            name='curated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='barangay',
            field=models.CharField(default='BARANGAY', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='gps_datum',
            field=models.CharField(default='WGS84', max_length=200, verbose_name='GPS Datum'),
        ),
        migrations.AlterField(
            model_name='station',
            name='reef_name',
            field=models.CharField(default='REEF NAME', max_length=200),
            preserve_default=False,
        ),
    ]
