# Generated by Django 3.2.5 on 2022-02-09 16:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coredb', '0005_auto_20211126_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('barangay', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('country', models.CharField(default='Philippines', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CoastWalkSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('gps_datum', models.CharField(default='WGS84', max_length=200, verbose_name='GPS Datum')),
                ('gps_unit', models.CharField(max_length=200)),
                ('leader', models.CharField(max_length=200)),
                ('leader_affiliation', models.CharField(max_length=200)),
                ('leader_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('leader_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('curated', models.BooleanField(default=False)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredb.location')),
            ],
            options={
                'verbose_name': 'Coast Walk Survey',
                'verbose_name_plural': 'Coast Walk Surveys',
            },
        ),
        migrations.CreateModel(
            name='CoastalCompartmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('coastal_compartment', models.CharField(max_length=200)),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredb.coastwalksurvey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeachProfilingSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('gps_datum', models.CharField(default='WGS84', max_length=200, verbose_name='GPS Datum')),
                ('start_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('leader', models.CharField(max_length=200)),
                ('leader_affiliation', models.CharField(max_length=200)),
                ('leader_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('leader_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('curated', models.BooleanField(default=False)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredb.location')),
            ],
            options={
                'verbose_name': 'Beach Profile Survey',
                'verbose_name_plural': 'Beach Profile Surveys',
            },
        ),
        migrations.CreateModel(
            name='AL1Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('reef_name', models.CharField(max_length=200)),
                ('start_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('gps_datum', models.CharField(default='WGS84', max_length=200, verbose_name='GPS Datum')),
                ('type_of_management', models.CharField(choices=[('None', 'None'), ('Locally Managed MPA', 'Locally Managed MPA'), ('Nationally Managed MPA', 'Nationally Managed MPA')], max_length=200)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('curated', models.BooleanField(default=False)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredb.location')),
            ],
            options={
                'verbose_name': 'Survey Station',
                'verbose_name_plural': 'Survey Stations',
                'unique_together': {('start_point', 'end_point')},
            },
        ),
        migrations.AlterField(
            model_name='al1survey',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredb.al1station'),
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
